//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.42
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seasar.Windows {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SWFMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SWFMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seasar.Windows.SWFMessages", typeof(SWFMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Form is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASWF0001 {
            get {
                return ResourceManager.GetString("ASWF0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter {0} is null or empty. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0001 {
            get {
                return ResourceManager.GetString("FSWF0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter {0} is under zero. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0002 {
            get {
                return ResourceManager.GetString("FSWF0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter {0} exceeds row number. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0003 {
            get {
                return ResourceManager.GetString("FSWF0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter startRow is larger than parameter endRow. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0004 {
            get {
                return ResourceManager.GetString("FSWF0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameter {0} is under 1. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0005 {
            get {
                return ResourceManager.GetString("FSWF0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid type : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FSWF0006 {
            get {
                return ResourceManager.GetString("FSWF0006", resourceCulture);
            }
        }
    }
}
