//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.1
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
/// </summary>
// このクラスは StronglyTypedResourceBuilder クラスが ResGen
// または Visual Studio のようなツールを使用して自動生成されました。
// メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
// ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class SSRMessages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal SSRMessages() {
    }
    
    /// <summary>
    ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SSRMessages", typeof(SSRMessages).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
    ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Physical connection closed に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0001 {
        get {
            return ResourceManager.GetString("DSSR0001", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Logical connection closed に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0002 {
        get {
            return ResourceManager.GetString("DSSR0002", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Transaction began に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0003 {
        get {
            return ResourceManager.GetString("DSSR0003", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Transaction committed に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0004 {
        get {
            return ResourceManager.GetString("DSSR0004", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Transaction rolledback に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0005 {
        get {
            return ResourceManager.GetString("DSSR0005", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Physical connection got に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0006 {
        get {
            return ResourceManager.GetString("DSSR0006", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Logical connection got に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string DSSR0007 {
        get {
            return ResourceManager.GetString("DSSR0007", resourceCulture);
        }
    }
    
    /// <summary>
    ///   {0} not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0001 {
        get {
            return ResourceManager.GetString("ESSR0001", resourceCulture);
        }
    }
    
    /// <summary>
    ///   &lt;{0}&gt; expected:&lt;{1}&gt; but actual:&lt;{2}&gt; に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0002 {
        get {
            return ResourceManager.GetString("ESSR0002", resourceCulture);
        }
    }
    
    /// <summary>
    ///   &lt;{0}&gt; unexpected:&lt;{1}&gt; に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0003 {
        get {
            return ResourceManager.GetString("ESSR0003", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not acquire section:{1} from {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0005 {
        get {
            return ResourceManager.GetString("ESSR0005", resourceCulture);
        }
    }
    
    /// <summary>
    ///   {0} should not be null or empty に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0007 {
        get {
            return ResourceManager.GetString("ESSR0007", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Exception occurred, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0017 {
        get {
            return ResourceManager.GetString("ESSR0017", resourceCulture);
        }
    }
    
    /// <summary>
    ///   IllegalState({0}) に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0026 {
        get {
            return ResourceManager.GetString("ESSR0026", resourceCulture);
        }
    }
    
    /// <summary>
    ///   unexpected {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0032 {
        get {
            return ResourceManager.GetString("ESSR0032", resourceCulture);
        }
    }
    
    /// <summary>
    ///   IOException occurred, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0040 {
        get {
            return ResourceManager.GetString("ESSR0040", resourceCulture);
        }
    }
    
    /// <summary>
    ///   {0}&apos;&apos;s creation failure, because {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0041 {
        get {
            return ResourceManager.GetString("ESSR0041", resourceCulture);
        }
    }
    
    /// <summary>
    ///   An illegal access was generated by {0}, because {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0042 {
        get {
            return ResourceManager.GetString("ESSR0042", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The target which {0} invoked is illegal, because {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0043 {
        get {
            return ResourceManager.GetString("ESSR0043", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Class not found, details are {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0044 {
        get {
            return ResourceManager.GetString("ESSR0044", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Two or more components({1}) are registered in {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0045 {
        get {
            return ResourceManager.GetString("ESSR0045", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Component({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0046 {
        get {
            return ResourceManager.GetString("ESSR0046", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The circulation reference was occurred in {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0047 {
        get {
            return ResourceManager.GetString("ESSR0047", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The constructor of {0} for args({1}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0048 {
        get {
            return ResourceManager.GetString("ESSR0048", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The method({1}) of {0} not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0049 {
        get {
            return ResourceManager.GetString("ESSR0049", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not parse, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0050 {
        get {
            return ResourceManager.GetString("ESSR0050", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Variable({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0051 {
        get {
            return ResourceManager.GetString("ESSR0051", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Target of property({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0052 {
        get {
            return ResourceManager.GetString("ESSR0052", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Bad parser configuration, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0053 {
        get {
            return ResourceManager.GetString("ESSR0053", resourceCulture);
        }
    }
    
    /// <summary>
    ///   SAXException occured, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0054 {
        get {
            return ResourceManager.GetString("ESSR0054", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Resource({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0055 {
        get {
            return ResourceManager.GetString("ESSR0055", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Attribute({1}) of tag({0}) not defined に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0056 {
        get {
            return ResourceManager.GetString("ESSR0056", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Method({1}) of class({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0057 {
        get {
            return ResourceManager.GetString("ESSR0057", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not configure constructor of {0}, because {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0058 {
        get {
            return ResourceManager.GetString("ESSR0058", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not configure property({1}) of {0}, because {2} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0059 {
        get {
            return ResourceManager.GetString("ESSR0059", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not configure method({1}) of {0}, because {2} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0060 {
        get {
            return ResourceManager.GetString("ESSR0060", resourceCulture);
        }
    }
    
    /// <summary>
    ///   SystemException occured, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0061 {
        get {
            return ResourceManager.GetString("ESSR0061", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Connection is closed に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0062 {
        get {
            return ResourceManager.GetString("ESSR0062", resourceCulture);
        }
    }
    
    /// <summary>
    ///   RollbackException occured, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0063 {
        get {
            return ResourceManager.GetString("ESSR0063", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Constructor({1}) of class({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0064 {
        get {
            return ResourceManager.GetString("ESSR0064", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Property({1}) of class({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0065 {
        get {
            return ResourceManager.GetString("ESSR0065", resourceCulture);
        }
    }
    
    /// <summary>
    ///   NamingException occurred, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0066 {
        get {
            return ResourceManager.GetString("ESSR0066", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Table({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0067 {
        get {
            return ResourceManager.GetString("ESSR0067", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Column({1}) of Table({0})not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0068 {
        get {
            return ResourceManager.GetString("ESSR0068", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Actual class ({1}) is not applicable in defined class ({0}) に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0069 {
        get {
            return ResourceManager.GetString("ESSR0069", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Field({1}) of class({0}) not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0070 {
        get {
            return ResourceManager.GetString("ESSR0070", resourceCulture);
        }
    }
    
    /// <summary>
    ///   SQLException occured, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0071 {
        get {
            return ResourceManager.GetString("ESSR0071", resourceCulture);
        }
    }
    
    /// <summary>
    ///   JScriptException occured, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0073 {
        get {
            return ResourceManager.GetString("ESSR0073", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Extension not found in {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0074 {
        get {
            return ResourceManager.GetString("ESSR0074", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The container of ({0}) has not been registered yet. に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0075 {
        get {
            return ResourceManager.GetString("ESSR0075", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Can not configure field of {0}, because {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0076 {
        get {
            return ResourceManager.GetString("ESSR0076", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Unable to commit, tx={0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0303 {
        get {
            return ResourceManager.GetString("ESSR0303", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already started preparing に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0304 {
        get {
            return ResourceManager.GetString("ESSR0304", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already prepared に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0305 {
        get {
            return ResourceManager.GetString("ESSR0305", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already started committing に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0306 {
        get {
            return ResourceManager.GetString("ESSR0306", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already committed に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0307 {
        get {
            return ResourceManager.GetString("ESSR0307", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already marked for rollback に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0308 {
        get {
            return ResourceManager.GetString("ESSR0308", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already started rolling back に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0309 {
        get {
            return ResourceManager.GetString("ESSR0309", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already rolled back に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0310 {
        get {
            return ResourceManager.GetString("ESSR0310", resourceCulture);
        }
    }
    
    /// <summary>
    ///   No transaction に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0311 {
        get {
            return ResourceManager.GetString("ESSR0311", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Unknown state に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0312 {
        get {
            return ResourceManager.GetString("ESSR0312", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Illegal status: {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0313 {
        get {
            return ResourceManager.GetString("ESSR0313", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already suspended に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0314 {
        get {
            return ResourceManager.GetString("ESSR0314", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Not suspended に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0315 {
        get {
            return ResourceManager.GetString("ESSR0315", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Nested transactions not supported に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0316 {
        get {
            return ResourceManager.GetString("ESSR0316", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Already associated with another transaction に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0317 {
        get {
            return ResourceManager.GetString("ESSR0317", resourceCulture);
        }
    }
    
    /// <summary>
    ///   TMJOIN is not supported に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0318 {
        get {
            return ResourceManager.GetString("ESSR0318", resourceCulture);
        }
    }
    
    /// <summary>
    ///   {0} is not same {1} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0319 {
        get {
            return ResourceManager.GetString("ESSR0319", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Status must be RS_SUCCESS に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0320 {
        get {
            return ResourceManager.GetString("ESSR0320", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Status must be RS_PREPARED に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0321 {
        get {
            return ResourceManager.GetString("ESSR0321", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Status must be RS_FAIL or RS_PREPARED に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0322 {
        get {
            return ResourceManager.GetString("ESSR0322", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Status must be RS_SUSPENDED に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0323 {
        get {
            return ResourceManager.GetString("ESSR0323", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Status must be RS_ACTIVE に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0324 {
        get {
            return ResourceManager.GetString("ESSR0324", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Too many rows に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0362 {
        get {
            return ResourceManager.GetString("ESSR0362", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Suspend failure, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0363 {
        get {
            return ResourceManager.GetString("ESSR0363", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Resume failure, because {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0364 {
        get {
            return ResourceManager.GetString("ESSR0364", resourceCulture);
        }
    }
    
    /// <summary>
    ///   To open connection is failure. Please check if database is started, connection string, provider. に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ESSR0365 {
        get {
            return ResourceManager.GetString("ESSR0365", resourceCulture);
        }
    }
    
    /// <summary>
    ///   seasar started に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ISSR0001 {
        get {
            return ResourceManager.GetString("ISSR0001", resourceCulture);
        }
    }
    
    /// <summary>
    ///   seasar stopped に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ISSR0002 {
        get {
            return ResourceManager.GetString("ISSR0002", resourceCulture);
        }
    }
    
    /// <summary>
    ///   seasar shutdown に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ISSR0003 {
        get {
            return ResourceManager.GetString("ISSR0003", resourceCulture);
        }
    }
    
    /// <summary>
    ///   {0} restarted に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string ISSR0005 {
        get {
            return ResourceManager.GetString("ISSR0005", resourceCulture);
        }
    }
    
    /// <summary>
    ///   &lt;&lt; server side stack trace &gt;&gt; に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0003 {
        get {
            return ResourceManager.GetString("WSSR0003", resourceCulture);
        }
    }
    
    /// <summary>
    ///   &lt;&lt; RemoteException stack trace &gt;&gt; に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0004 {
        get {
            return ResourceManager.GetString("WSSR0004", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Illegal transaction rolledback に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0005 {
        get {
            return ResourceManager.GetString("WSSR0005", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Execution at {0} failovered に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0006 {
        get {
            return ResourceManager.GetString("WSSR0006", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Assign null, because constructorArg({1}) of {0} not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0007 {
        get {
            return ResourceManager.GetString("WSSR0007", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Skip setting property, because property({1}) of {0} not found に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0008 {
        get {
            return ResourceManager.GetString("WSSR0008", resourceCulture);
        }
    }
    
    /// <summary>
    ///   The qualifier not applicable as for the aspect is specified by method ({1}) of {0} に類似しているローカライズされた文字列を検索します。
    /// </summary>
    internal static string WSSR0009 {
        get {
            return ResourceManager.GetString("WSSR0009", resourceCulture);
        }
    }
}
