//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3082
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seasar.Dxo {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DxoMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DxoMessages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Seasar.Dxo.DxoMessages", typeof(DxoMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} cannot be instantiated because this class is concrete class. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDXO0001 {
            get {
                return ResourceManager.GetString("EDXO0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be not null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDXO1001 {
            get {
                return ResourceManager.GetString("EDXO1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be compatible with {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDXO1002 {
            get {
                return ResourceManager.GetString("EDXO1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be compatible with IDictionary&lt;{1}{2}&gt;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDXO1003 {
            get {
                return ResourceManager.GetString("EDXO1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} must be {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EDXO1004 {
            get {
                return ResourceManager.GetString("EDXO1004", resourceCulture);
            }
        }
    }
}
